"""Background task that drains Polymarket fills into the on-chain router.

For each market we own:

  1. Poll :meth:`PolymarketV2Client.list_fills` every ``poll_interval``
     seconds.
  2. For every previously-unseen fill, call
     ``BuilderFeeRouter.recordFill(marketId, fillAmount, translator)``
     on Arc testnet via ``web3.py``.
  3. Emit an SSE-shaped dict to the configured sink so the FastAPI
     backend can fan it out to the UI.
  4. Persist a ``BuilderFeeEvent`` row through the supplied callback.

The contract address comes from env ``BUILDER_FEE_ROUTER_ADDRESS`` and
the signer from ``OPERATOR_WALLET_PRIVATE_KEY`` (we fall back to
``HACKATHON_WALLET_PRIVATE_KEY`` for local dev — the hackathon wallet
is the deployer of the router so it's already the operator). When
chain credentials are absent we still emit SSE + DB rows but skip the
``recordFill`` call and mark ``on_chain_status="skipped"``.
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
import time
from pathlib import Path
from typing import Awaitable, Callable, Optional, Protocol

from polyglot_alpha.polymarket.types import BuilderFeeEvent, Fill

log = logging.getLogger(__name__)

DEFAULT_POLL_INTERVAL_SECONDS = 30
USDC_DECIMALS = 6  # both real and Arc-testnet MockUSDC use 6 decimals.

# Path to the compiled router ABI. Generated by `forge build`.
_DEFAULT_ROUTER_ABI_PATH = (
    Path(__file__).resolve().parents[2]
    / "contracts"
    / "out"
    / "BuilderFeeRouter.sol"
    / "BuilderFeeRouter.json"
)


class _FillSource(Protocol):
    async def list_fills(
        self, market_id: str, since_ts: int
    ) -> list[Fill]:  # pragma: no cover - structural
        ...


SSESink = Callable[[dict], Awaitable[None]]
DBSink = Callable[[BuilderFeeEvent], Awaitable[None]]


class FillListener:
    """Drains fills for a single (market_id, translator) pairing.

    Construct one per submission so each listener has its own polling
    cursor. Run with :meth:`listen` (forever, for production) or
    :meth:`poll_once` (for tests / single demo ticks).
    """

    def __init__(
        self,
        *,
        client: _FillSource,
        market_id: str,
        translator_address: str,
        poll_interval: int = DEFAULT_POLL_INTERVAL_SECONDS,
        sse_sink: Optional[SSESink] = None,
        db_sink: Optional[DBSink] = None,
        chain_recorder: Optional["ChainRecorder"] = None,
        time_fn: Callable[[], float] = time.time,
    ) -> None:
        if not market_id:
            raise ValueError("market_id is required")
        if not translator_address or not translator_address.startswith("0x"):
            raise ValueError("translator_address must be a 0x-prefixed EVM address")
        self._client = client
        self.market_id = market_id
        self.translator_address = translator_address
        self.poll_interval = poll_interval
        self._sse_sink = sse_sink
        self._db_sink = db_sink
        self._chain = chain_recorder
        self._time_fn = time_fn
        # Newest timestamp we've already drained. Start "now" so we
        # don't replay every historical fill on a cold start.
        self._cursor_ts: int = int(time_fn())
        self._seen_fill_ids: set[str] = set()
        self._stop = asyncio.Event()

    # ----- public ops ----------------------------------------------------

    async def poll_once(self) -> list[BuilderFeeEvent]:
        """One polling tick — process all new fills and return the events."""
        fills = await self._client.list_fills(self.market_id, self._cursor_ts)
        events: list[BuilderFeeEvent] = []
        for fill in fills:
            if fill.fill_id in self._seen_fill_ids:
                continue
            self._seen_fill_ids.add(fill.fill_id)
            event = await self._process_fill(fill)
            events.append(event)
            if fill.timestamp > self._cursor_ts:
                self._cursor_ts = fill.timestamp
        return events

    async def listen(self) -> None:
        """Poll forever until :meth:`stop` is called."""
        log.info(
            "FillListener starting market=%s translator=%s interval=%ss",
            self.market_id,
            self.translator_address,
            self.poll_interval,
        )
        while not self._stop.is_set():
            try:
                await self.poll_once()
            except Exception:  # noqa: BLE001 — never let a poll kill the loop
                log.exception(
                    "FillListener poll failed for market=%s", self.market_id
                )
            try:
                await asyncio.wait_for(
                    self._stop.wait(), timeout=self.poll_interval
                )
            except asyncio.TimeoutError:
                continue

    def stop(self) -> None:
        self._stop.set()

    # ----- internals -----------------------------------------------------

    async def _process_fill(self, fill: Fill) -> BuilderFeeEvent:
        event = BuilderFeeEvent(
            fill_id=fill.fill_id,
            market_id=fill.market_id,
            translator_address=self.translator_address,
            fill_amount_usdc=fill.fill_amount_usdc,
            builder_fee_usdc=fill.builder_fee_usdc,
            is_simulated=fill.is_simulated,
            timestamp=fill.timestamp,
        )

        if self._chain is not None:
            try:
                tx_hash = await self._chain.record_fill(
                    market_id=fill.market_id,
                    fill_amount_usdc=fill.builder_fee_usdc,
                    translator_address=self.translator_address,
                )
                event.tx_hash = tx_hash
                event.on_chain_status = "confirmed" if tx_hash else "skipped"
            except Exception as exc:  # noqa: BLE001
                log.exception(
                    "recordFill on chain failed for fill=%s", fill.fill_id
                )
                event.on_chain_status = "failed"
                event.tx_hash = None
                event = event.model_copy(update={"on_chain_status": "failed"})
                # Keep going — we still want the SSE + DB row so the UI
                # can flag the failure.
                _ = exc
        else:
            event.on_chain_status = "skipped"

        if self._db_sink is not None:
            try:
                await self._db_sink(event)
            except Exception:  # noqa: BLE001
                log.exception("DB sink failed for fill=%s", fill.fill_id)

        if self._sse_sink is not None:
            try:
                await self._sse_sink(
                    {
                        "type": "builder_fee.accrued",
                        "data": event.model_dump(),
                    }
                )
            except Exception:  # noqa: BLE001
                log.exception("SSE sink failed for fill=%s", fill.fill_id)

        return event


# ---------------------------------------------------------------------------
# On-chain recorder
# ---------------------------------------------------------------------------


class ChainRecorder:
    """Wraps ``BuilderFeeRouter.recordFill`` calls via web3.py.

    Kept in this module to keep the polymarket package self-contained;
    nothing else in the codebase needs it. Constructing one is cheap and
    safe even when the chain creds are missing — it will simply refuse
    to send and return ``None`` from :meth:`record_fill`.
    """

    def __init__(
        self,
        *,
        rpc_url: Optional[str] = None,
        router_address: Optional[str] = None,
        private_key: Optional[str] = None,
        abi_path: Optional[Path] = None,
        chain_id: Optional[int] = None,
    ) -> None:
        self.rpc_url = rpc_url or os.getenv("ARC_TESTNET_RPC")
        self.router_address = router_address or os.getenv(
            "BUILDER_FEE_ROUTER_ADDRESS"
        )
        self.private_key = private_key or os.getenv(
            "OPERATOR_WALLET_PRIVATE_KEY"
        ) or os.getenv("HACKATHON_WALLET_PRIVATE_KEY")
        raw_chain = chain_id or os.getenv("ARC_CHAIN_ID")
        self.chain_id = int(raw_chain) if raw_chain else None
        self._abi_path = abi_path or _DEFAULT_ROUTER_ABI_PATH
        self._w3 = None
        self._contract = None
        self._account = None

    @property
    def enabled(self) -> bool:
        return bool(
            self.rpc_url
            and self.router_address
            and self.private_key
            and self._abi_path.exists()
        )

    def _lazy_init(self) -> bool:
        """Defer web3 import until we actually need it (keeps tests fast)."""
        if self._contract is not None:
            return True
        if not self.enabled:
            return False
        try:
            from eth_account import Account  # type: ignore
            from web3 import Web3  # type: ignore
        except ImportError:  # pragma: no cover - web3 is in requirements
            log.warning("web3 not installed; ChainRecorder disabled")
            return False

        with self._abi_path.open("r", encoding="utf-8") as fh:
            artifact = json.load(fh)
        abi = artifact.get("abi", artifact)

        self._w3 = Web3(Web3.HTTPProvider(self.rpc_url))
        self._account = Account.from_key(self.private_key)
        self._contract = self._w3.eth.contract(
            address=Web3.to_checksum_address(self.router_address), abi=abi
        )
        return True

    async def record_fill(
        self,
        *,
        market_id: str,
        fill_amount_usdc: float,
        translator_address: str,
    ) -> Optional[str]:
        """Send the on-chain transaction and return the tx hash hex.

        Returns ``None`` when disabled (missing env / ABI) so callers
        can label the event "skipped" instead of "failed".
        """
        if not self._lazy_init():
            return None
        # web3 calls are blocking — push them to a thread to keep the
        # asyncio loop responsive.
        return await asyncio.to_thread(
            self._send_record_fill_sync,
            market_id,
            fill_amount_usdc,
            translator_address,
        )

    def _send_record_fill_sync(
        self,
        market_id: str,
        fill_amount_usdc: float,
        translator_address: str,
    ) -> str:
        from web3 import Web3  # type: ignore

        assert self._w3 is not None and self._contract is not None
        amount_base = int(round(fill_amount_usdc * (10**USDC_DECIMALS)))
        if amount_base <= 0:
            raise ValueError("fill_amount_usdc must be > 0 (after scaling)")

        translator = Web3.to_checksum_address(translator_address)
        nonce = self._w3.eth.get_transaction_count(self._account.address)
        tx = self._contract.functions.recordFill(
            market_id, amount_base, translator
        ).build_transaction(
            {
                "from": self._account.address,
                "nonce": nonce,
                "chainId": self.chain_id
                or self._w3.eth.chain_id,
                "gas": 250_000,
                "gasPrice": self._w3.eth.gas_price,
            }
        )
        signed = self._account.sign_transaction(tx)
        tx_hash = self._w3.eth.send_raw_transaction(signed.raw_transaction)
        return tx_hash.hex()
